feat: introduce multiple verifiers per security model
sygmaprotocol/sygma-x-solidity pull request #23
Opened 2024-02-07 11:45 UTC by nmlinaric

## Description
- introduces multiple verifiers per security model
- add admin method for setting the above

## Related Issue Or Context
Closes: #21 

## How Has This Been Tested? Testing details.
Unit tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [x] I have updated the documentation locally and in Sygma-docs.
- [x] I have added tests to cover my changes.
- [x] I have ensured that all the checks are passing and green, I've signed the CLA bot

2024-02-07 14:32 UTC, mpetrun5 approved these changes

2024-02-12 09:09 UTC, lastperson requested changes

2024-02-12 09:09 UTC, lastperson commented on src/contracts/Executor.sol
> +            for (uint256 j = 1; j < _securityModels[proposals[i].securityModel].length; j++) {
Could read the length into a local var to reduce the number of storage reads.

2024-02-12 09:09 UTC, lastperson commented on src/contracts/Executor.sol
> +        _securityModels[securityModel] = verifiersAddresses;
Should it require the verifiers length to be at least 1?

2024-02-12 09:09 UTC, lastperson commented on src/contracts/Executor.sol
> +                if(expectedStateRoot != stateRoot) revert StateRootDoesNotMatch(stateRoot);
Maybe it makes sense to add the verifier address or index to the error for debug purposes?

2024-02-12 11:22 UTC, lastperson approved these changes

2024-02-12 11:45 UTC, merged