fix: add zero address constructor checks
sygmaprotocol/sygma-x-solidity pull request #39
Opened 2024-03-12 12:58 UTC by nmlinaric

## Description
Adds zero address constructor checks

## How Has This Been Tested? Testing details.
unit tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in Sygma-docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

2024-03-12 13:00 UTC, mpetrun5 approved these changes

2024-03-13 08:09 UTC, lastperson requested changes

2024-03-13 08:09 UTC, lastperson commented on src/contracts/Executor.sol
> +        if(bridge == address(0) ||accessControl == address(0)) revert ZeroAddressProvided();
```suggestion
        if (bridge == address(0) || accessControl == address(0)) revert ZeroAddressProvided();
```

2024-03-13 08:09 UTC, lastperson commented on src/contracts/Router.sol
> +        if(bridge == address(0) ||accessControl == address(0)) revert ZeroAddressProvided();
```suggestion
        if (bridge == address(0) || accessControl == address(0)) revert ZeroAddressProvided();
```

2024-03-13 08:09 UTC, lastperson commented on src/contracts/Bridge.sol
> +        if(accessControl == address(0)) revert ZeroAddressProvided();
```suggestion
        if (accessControl == address(0)) revert ZeroAddressProvided();
```

2024-03-14 06:13 UTC, lastperson approved these changes

2024-03-15 08:58 UTC, merged