chore: add description about transferHashes mapping usage
sygmaprotocol/sygma-x-solidity pull request #40
Opened 2024-03-12 13:09 UTC by nmlinaric

## Description
Add description about transferHashes mapping usage

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in Sygma-docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

2024-03-12 13:11 UTC, mpetrun5 approved these changes

2024-03-13 08:10 UTC, lastperson requested changes

2024-03-13 08:10 UTC, lastperson commented on src/contracts/Router.sol
> +    // the EVM state so it can proved in the Executor contract via state proof
```suggestion
    // the EVM state so it can be proved in the Executor contract via state proof
```

2024-03-14 06:13 UTC, lastperson approved these changes

2024-03-15 08:58 UTC, merged