chore: remove unused imports, excess casting and fix func visibility
sygmaprotocol/sygma-x-solidity pull request #41
Opened 2024-03-13 11:41 UTC by nmlinaric

## Description
Maintainability improvements - remove unused imports, fix function visibility,...

## How Has This Been Tested? Testing details.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in Sygma-docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

2024-03-13 11:57 UTC, mpetrun5 requested changes

2024-03-13 11:57 UTC, mpetrun5 commented on src/contracts/handlers/ERC20Handler.sol
> +    ) external override onlyBridgeRouterOrExecutor returns (bytes memory) {
I would keep most of these as onlyBridge because Router or Executor don't even have a way to call them.

2024-03-13 13:03 UTC, lastperson requested changes

2024-03-13 13:03 UTC, lastperson commented on src/contracts/Router.sol
> +    // this is used to prove in executor validit of data via state proof
```suggestion
    // this is used to prove in executor validity of data via state proof
```

2024-03-14 06:16 UTC, lastperson requested changes

2024-03-14 06:16 UTC, lastperson commented on src/contracts/Executor.sol
> +            address handler = _bridge._resourceIDToHandlerAddress(proposals[i].resourceID);
```suggestion
            address handler = _bridge._resourceIDToHandlerAddress(proposal.resourceID);
```

2024-03-14 06:17 UTC, lastperson approved these changes

2024-03-15 09:12 UTC, lastperson commented
Force-pushes makes subsequent reviews more time consuming.

2024-03-18 14:24 UTC, mpetrun5 approved these changes

2024-03-18 14:24 UTC, merged